language: python

before_install:
  - export TZ='Asia/Shanghai'
  
install: true

script: true

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - zjpjzdl@qq.com
    on_success: always # default: change
    on_failure: always # default: always